### ISSUE TITLE
The application crashes when I try to open the application

### ISSUE THREAD

**Issue by friendsmobile** [apps4bali/gatrabali-app#1]
<table class="">
 <tbody>
  <tr>
   <th scope="row">-----------------------------</a>Project Information-------------------------------------</th>
   <td>.</td>
  </tr>
  <tr>

<table class="properties">
 <tbody>
  <tr>
   <th scope="row">Project Respotry</a></th>
   <td>https://github.com/apps4bali/gatrabali-app.</td>
  </tr>
  <tr>
   <th scope="row">Project Name:</th>
   <td>gatrabali-app</a>.</td>
  </tr>
  <tr>
   <th scope="row">My Github Account</th>
   <td>  https://github.com/friendsmobile.</td>
  </tr>
  <tr>
   <th scope="row"> APK Downlod </th>
   <td> <h1><h6>https://play.google.com/store/apps/details?id=com.gatrabali.android</td>
  </tr
  <tr>
   <th scope="row">
  <td> 
  </tr>
  <tr>

 </tbody>
</table>
</stope>
</end>

#### Expected behavior 

The application should not crash when I try to open the application

#### Actual behavior

The application crashes when I try to open the application

#### How to reproduce

* open the application
*  try to open the application
* Note the Error

* Browser/App version: 1.0.4
* Operating system: 6.0

#### Recording Of The Bug

![20190701_093114](https://user-images.githubusercontent.com/51118734/60411640-8c18cc80-9b82-11e9-9149-3f21812cd705.gif)

#### Logcat

<pre><code>D/AndroidRuntime(17425): Shutting down VM

E/AndroidRuntime(17425): FATAL EXCEPTION: main

E/AndroidRuntime(17425): Process: com.gatrabali.android, PID: 17425

E/AndroidRuntime(17425): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.gatrabali.android-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libflutter.so"

E/AndroidRuntime(17425): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)

E/AndroidRuntime(17425): 	at java.lang.System.loadLibrary(System.java:988)

E/AndroidRuntime(17425): 	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:161)

E/AndroidRuntime(17425): 	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:136)

E/AndroidRuntime(17425): 	at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)

E/AndroidRuntime(17425): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1019)

E/AndroidRuntime(17425): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4991)

E/AndroidRuntime(17425): 	at android.app.ActivityThread.access$1600(ActivityThread.java:177)

E/AndroidRuntime(17425): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1491)

E/AndroidRuntime(17425): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(17425): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(17425): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(17425): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(17425): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(17425): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(17425): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by ekaputra07** [comment]
Thanks @friendsmobile for the detailed crash report, I really appreciate it.
Will have a look at it and keep you updated on the progress.

**Comment by friendsmobile** [comment]
welcome sir
